<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Compat\RWVDCS.CompatProtocol\RWVDCS.CompatProtocol.csproj" />
    <ProjectReference Include="..\..\Core\RWVDCS.Core\RWVDCS.Core.csproj" />
    <ProjectReference Include="..\..\Core\RWVDCS.Hosting\RWVDCS.Hosting.csproj" />
    <ProjectReference Include="..\..\Engineering\RWVDCS.Engineering\RWVDCS.Engineering.csproj" />
    <ProjectReference Include="..\..\Runtime\RWVDCS.Runtime\RWVDCS.Runtime.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="wwwroot\**" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

</Project>
